# Generated by Django 5.2.5 on 2025-09-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen ilustrativa del post', null=True, upload_to='posts/'),
        ),
    ]
