# Generated by Django 5.2.5 on 2025-09-04 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_post_meta_description_post_meta_keywords_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(help_text='Tags separados por comas para buscar noticias', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SEARCHING', 'Buscando noticias'), ('GENERATING', 'Generando contenido'), ('COMPLETED', 'Completado'), ('ERROR', 'Error'), ('PUBLISHED', 'Publicado')], default='PENDING', max_length=20)),
                ('generated_title', models.CharField(blank=True, max_length=200)),
                ('generated_excerpt', models.CharField(blank=True, max_length=300)),
                ('generated_content', models.TextField(blank=True, help_text='Contenido en formato HTML')),
                ('generated_meta_description', models.CharField(blank=True, max_length=160)),
                ('generated_meta_keywords', models.CharField(blank=True, max_length=255)),
                ('source_articles', models.JSONField(default=list, help_text='Lista de artículos fuente con URLs y metadata')),
                ('total_sources_found', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('published_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post', verbose_name='Post publicado')),
            ],
            options={
                'verbose_name': 'Generación de Noticia IA',
                'verbose_name_plural': 'Generaciones de Noticias IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
