# Generated by Django 5.2.5 on 2025-09-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_newsgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsgeneration',
            name='manual_urls',
            field=models.TextField(blank=True, help_text='URLs manuales separadas por saltos de línea (opcional - si se proporcionan, se usarán en lugar de búsqueda automática)'),
        ),
    ]
